=== thiyagavit/passerelle/tags/V8.6.0/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/dtd/plugin_config_file.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT plugin-config  (dataset-model*,global?)>
<!ATTLIST plugin-config 
    name CDATA #REQUIRED
>

<!-- 
==========================
global
========================== 
-->
<!ELEMENT global (java? | cpp?)>
<!ELEMENT java (set*)>
<!ELEMENT cpp (set*)>
<!ELEMENT set EMPTY>
<!ATTLIST set 
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>

<!--
==========================
dataset_model
========================== 
-->
<!ELEMENT dataset-model (criteria? , parameters? , plugin? )>
<!ATTLIST dataset-model 
    name CDATA #REQUIRED
>
    
<!--
==========================
plugin
========================== 
--> 
<!ELEMENT plugin ( java? | cpp? )>


<!--
==========================
criteria
========================== 
-->
<!ELEMENT criteria (if*)>
<!ELEMENT if EMPTY>
<!ATTLIST if 
    target CDATA #REQUIRED
    exist ( true | false ) #IMPLIED
    equal CDATA #IMPLIED
    not_equal CDATA #IMPLIED
>


<!--
==========================
parameters
========================== 
-->
<!ELEMENT parameters (parameter*)>
<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
    name CDATA #REQUIRED
    type ( exist | name | value | constant | equal ) #REQUIRED
    test ( true | false ) #IMPLIED
    target CDATA #IMPLIED
    constant CDATA #IMPLIED
>

=== thiyagavit/passerelle/trunk/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/mappings/SoleilNeXus/cdma_nexussoleil_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin-config SYSTEM "../../dtd/plugin_config_file.dtd">
<plugin-config name="SOLEIL's NeXus plug-in configuration file">


<!-- ============================================
==  CONFIG 1: detection by file information    ==
============================================= -->
  <dataset-model name="fully_defined_conf">
    <criteria>
      <if exist="true" target="/{NXinstrument}"/>
      <if exist="true" target="/acquisition_model"/>
    </criteria>

    <parameters> 
      <parameter name="BEAMLINE" type="name" target="/{NXinstrument}"/>
      <parameter name="MODEL" type="value" target="/acquisition_model"/>
    </parameters>

    <plugin>
      <java>
        <set name="log_debug" value="true"/>
        <set name="N4T_buffer_size" value="300"/>
      </java>
    </plugin>
  </dataset-model>

<!-- ============================================
==  CONFIG 2: all beamlines scanserver         ==
============================================= -->
  <dataset-model name="generic_scanserver">
    <criteria>
      <if exist="true" target="/{NXinstrument}"/>
      <if exist="true" target="/scan_data{NXdata}/data_01"/>
    </criteria>
    
    <parameters>
      <parameter name="BEAMLINE" type="name" target="/{NXinstrument}"/>
      <parameter name="MODEL" type="constant" constant="scanserver"/>
    </parameters>

    <plugin>
      <java>
        <set name="log_debug" value="true"/>
        <set name="N4T_buffer_size" value="300"/>
      </java>
    </plugin>
  </dataset-model>
  
<!-- ============================================
==  CONFIG 3: all beamlines passerelle         ==
============================================= -->
  <dataset-model name="generic_passerelle">
    <criteria>
      <if exist="true" target="/{NXinstrument}"/>
    </criteria>
    
    <parameters>
      <parameter name="BEAMLINE" type="name" target="/{NXinstrument}"/>
      <parameter name="MODEL" type="constant" constant="passerelle"/>
    </parameters>

    <plugin>
      <java>
        <set name="log_debug" value="true"/>
        <set name="N4T_buffer_size" value="300"/>
      </java>
    </plugin>
  </dataset-model>
  
<!-- ============================================
==  CONFIG 4: all beamlines flyscan            ==
============================================= -->
  <dataset-model name="generic_flyscan">
    <criteria>
      <if exist="true" target="/*flyscan*{NXentry}/{NXinstrument}" />
    </criteria>
    
    <parameters>
      <parameter name="BEAMLINE" type="name" target="/{NXentry}/{NXinstrument}"/>
      <parameter name="MODEL" type="constant" constant="flyscan"/>
    </parameters>
    
    <plugin>
      <java>
        <set name="log_debug" value="true"/>
        <set name="N4T_buffer_size" value="300"/>
      </java>
    </plugin>
  </dataset-model>
  

<!-- ============================================
==  CONFIG 5: SAMBA quickexafs                       ==
============================================= -->
  <dataset-model name="samba_quickexafs">
    <criteria>
      <if exist="true" target="/{NXentry}/{NXdata}/DeltaTheta"/>
      <if exist="true" target="/{NXentry}/{NXdata}/channel0"/>
    </criteria>
    
    <parameters>
      <parameter name="BEAMLINE" type="constant" constant="samba"/>
      <parameter name="MODEL" type="constant" constant="quickexafs"/>
    </parameters>

    <plugin>
      <java>
        <set name="log_debug" value="true"/>
        <set name="N4T_buffer_size" value="300"/>
      </java>
    </plugin>
  </dataset-model>
  
<!-- ============================================
==  Global section                             ==
============================================= -->
  <global>
    <java>
     <set name="CDMA_DEBUG" value="true"/>
    </java>
  </global>
</plugin-config>

=== thiyagavit/passerelle/tags/V8.7.5/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/mappings/MamboSoleil/cdma_mambosoleil_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin-config SYSTEM "../../dtd/plugin_config_file.dtd">
<plugin-config name="SOLEIL's Mambo plug-in configuration file">


<!-- ============================================
==  CONFIG 1: detection by file information    ==
============================================= -->
  <dataset-model name="fully_defined_conf">
    <plugin>
      <java>
        <set name="HDB_RAC" value=""/>
        <set name="HDB_DRIVER" value="jdbc:oracle:thin"/>
        <set name="HDB_HOST" value="LUTIN"/>
        <set name="HDB_NAME" value="TEST11"/>
        <set name="HDB_PORT" value="1521"/>
        <set name="HDB_SCHEMA" value=""/>
        <!--
        <set name="HDB_USER" value=""/>
        <set name="HDB_PASSWORD" value=""/>
        -->
        <set name="TDB_RAC" value=""/>
        <set name="TDB_DRIVER" value="jdbc:oracle:thin"/>
        <set name="TDB_HOST" value="LUTIN"/>
        <set name="TDB_NAME" value="TEST11"/>
        <set name="TDB_PORT" value="1521"/>
        <set name="TDB_SCHEMA" value=""/>
        <!--
        <set name="TDB_USER" value=""/>
        <set name="TDB_PASSWORD" value=""/>
        -->
      </java>
    </plugin>
  </dataset-model>
</plugin-config>
