=== thiyagavit/passerelle/branches/passerelle-8.8/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/dtd/mapping_file.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT map-def (item*)>
<!ATTLIST map-def
    name CDATA #REQUIRED
    version CDATA #REQUIRED
>

<!-- 
==========================
item
========================== 
-->
<!ELEMENT item ( (path | call)*, attribute* )>
<!ATTLIST item 
    key CDATA #REQUIRED
>

<!-- 
==========================
item
========================== 
-->
<!ELEMENT path (#PCDATA)>
<!ATTLIST path >

<!-- 
==========================
item
========================== 
-->
<!ELEMENT call (#PCDATA)>
<!ATTLIST call >

<!--
==========================
dataset_model
========================== 
-->
<!ELEMENT attribute ( (path | call)* )>
<!ATTLIST attribute
    name CDATA #REQUIRED
    value CDATA #IMPLIED
>

=== thiyagavit/passerelle/tags/V8.6.0/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/mappings/SoleilNeXus/sextants_scanserver.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map-def SYSTEM "../../dtd/mapping_file.dtd">
<map-def name="SEXTANTS" version="1.0.0">
  <item key="acquisition_sequence">
    <path>/</path>
    <call>CreateVirtualItem</call>
  </item>
    <item key="dark">
        <path>/{NXinstrument}/{NXdetector}/intensityBlack</path>
    </item>
    <item key="distance">
        <path>/{NXinstrument}/{NXdetector}/distance</path>
    </item>
    <item key="exposureTime">
        <path>/{NXinstrument}/{NXdetector}/Exposure</path>
    </item>
    <item key="shutterCloseDelay">
        <path>/{NXinstrument}/{NXdetector}/ShutterCloseDelay</path>
    </item>
    <item key="xBin">
        <path>/{NXinstrument}/{NXdetector}/Xbin</path>
    </item>
    <item key="yBin">
        <path>/{NXinstrument}/{NXdetector}/Ybin</path>
    </item>
    <item key="mi">
        <path>/{NXinstrument}/{NXintensity_monitor}</path>
    </item>
    <item key="gain">
        <path>/{NXinstrument}/{NXintensity_monitor}/Gain</path>
    </item>
    <item key="intensity">
        <path>/{NXinstrument}/{NXintensity_monitor}/intensity</path>
    </item>
    <item key="lambda">
        <path>/{NXinstrument}/{NXmonochromator}/wavelength</path>
    </item>
    <item key="energy">
        <path>/{NXinstrument}/{NXmonochromator}/energy</path>
    </item>
    <item key="images">
        <path>/{NXdata}/data_01</path>
	    <call>HarvestSignalAttributes</call>
	    <attribute name="interpretation" value="image"/>
    </item>
    <item key="comments">
        <path>/{NXsample}/comments/data</path>
    </item>
</map-def>
