=== thiyagavit/passerelle/branches/passerelle-8.8/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/dtd/mapping_file.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT map-def (item*)>
<!ATTLIST map-def
    name CDATA #REQUIRED
    version CDATA #REQUIRED
>

<!-- 
==========================
item
========================== 
-->
<!ELEMENT item ( (path | call)*, attribute* )>
<!ATTLIST item 
    key CDATA #REQUIRED
>

<!-- 
==========================
item
========================== 
-->
<!ELEMENT path (#PCDATA)>
<!ATTLIST path >

<!-- 
==========================
item
========================== 
-->
<!ELEMENT call (#PCDATA)>
<!ATTLIST call >

<!--
==========================
dataset_model
========================== 
-->
<!ELEMENT attribute ( (path | call)* )>
<!ATTLIST attribute
    name CDATA #REQUIRED
    value CDATA #IMPLIED
>

=== thiyagavit/passerelle/trunk/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/mappings/SoleilNeXus/unknown_unknown.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map-def SYSTEM "../../dtd/mapping_file.dtd">
<map-def name="UNKNOWN" version="1.0.0">
    <item key="camera">
        <path>/{NXentry}/{NXinstrument}/$(detector_name){NXdetector}</path>
    </item>
    <item key="dark">
        <path>/{NXentry}/{NXinstrument}/{NXdetector}/intensityBlack</path>
    </item>
    <item key="distance">
        <path>/{NXentry}/{NXinstrument}/{NXdetector}/distance</path>
    </item>
    <item key="exposureTime">
        <path>/{NXentry}/{NXinstrument}/{NXdetector}/Exposure</path>
    </item>
    <item key="shutterCloseDelay">
        <path>/{NXentry}/{NXinstrument}/{NXdetector}/ShutterCloseDelay</path>
    </item>
    <item key="xBin">
        <path>/{NXentry}/{NXinstrument}/{NXdetector}/Xbin</path>
    </item>
    <item key="yBin">
        <path>/{NXentry}/{NXinstrument}/{NXdetector}/Ybin</path>
    </item>
    <item key="mi">
        <path>/{NXentry}/{NXinstrument}/{NXintensity_monitor}</path>
    </item>
    <item key="gain">
        <path>/{NXentry}/{NXinstrument}/{NXintensity_monitor}/Gain</path>
    </item>
    <item key="intensity">
        <path>/{NXentry}/{NXinstrument}/{NXintensity_monitor}/intensity</path>
    </item>
    <item key="lambda">
        <path>/{NXentry}/{NXinstrument}/{NXmonochromator}/wavelength</path>
    </item>
    <item key="energy">
        <path>/{NXentry}/{NXinstrument}/{NXmonochromator}/energy</path>
    </item>
    <item key="images">
        <path>/{NXentry}/{NXdata}/xpad1</path>
        <attribute name="interpretation" value="image"/>
    </item>
    <item key="comments">
        <path>/{NXentry}/{NXsample}/comments/data</path>
    </item>
</map-def>

=== thiyagavit/passerelle/branches/passerelle-8.10/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/mappings/SoleilNeXus/swing_scanserver.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map-def SYSTEM "../../dtd/mapping_file.dtd">
<map-def name="SWING" version="1.0.0">
    <item key="camera">
        <path>/{NXinstrument}/{NXdetector}</path>
    </item>
    <item key="dark">
        <path>/{NXinstrument}/{NXdetector}/intensityBlack</path>
    </item>
    <item key="distance">
        <path>/{NXinstrument}/{NXdetector}/distance</path>
    </item>
    <item key="exposureTime">
        <path>/{NXinstrument}/{NXdetector}/Exposure</path>
    </item>
    <item key="shutterCloseDelay">
        <path>/{NXinstrument}/{NXdetector}/ShutterCloseDelay</path>
    </item>
    <item key="xBin">
        <path>/{NXinstrument}/{NXdetector}/Xbin</path>
    </item>
    <item key="yBin">
        <path>/{NXinstrument}/{NXdetector}/Ybin</path>
    </item>
    <item key="mi">
        <path>/{NXinstrument}/{NXintensity_monitor}</path>
    </item>
    <item key="gain">
        <path>/{NXinstrument}/{NXintensity_monitor}/Gain</path>
    </item>
    <item key="intensity">
        <path>/{NXinstrument}/{NXintensity_monitor}/intensity</path>
    </item>
    <item key="lambda">
        <path>/{NXinstrument}/{NXmonochromator}/wavelength</path>
    </item>
    <item key="energy">
        <path>/{NXinstrument}/{NXmonochromator}/energy</path>
    </item>
    <item key="spectrums">
        <path>/{NXdata}/data*</path>
        <call>DataItemStacker</call>
        <attribute name="interpretation" value="spectrum"/>
    </item>
    <item key="comments">
        <path>/{NXsample}/comments/data</path>
    </item>
</map-def>

=== thiyagavit/passerelle/tags/V8.6.2/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/mappings/SoleilNeXus/samba_quickexafs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map-def SYSTEM "../../dtd/mapping_file.dtd">
<map-def name="QUICK_EXAFS" version="1.0.0">
    <item key="delta_theta">
        <path>/{NXentry}/{NXdata}/DeltaTheta</path>
    </item>
    <item key="intensity0">
        <path>/{NXentry}/{NXdata}/channel0*</path>
    </item>
    <item key="intensity1">
        <path>/{NXentry}/{NXdata}/channel1*</path>
    </item>
    <item key="intensity2">
        <path>/{NXentry}/{NXdata}/channel2*</path>
    </item>
    <item key="mono2_direction">
        <path>/{NXentry}/{NXdata}/mono2Direction*</path>
    </item>
    <item key="mono3_direction">
        <path>/{NXentry}/{NXdata}/mono3Direction*</path>
    </item>
    <item key="cristal_inter_reticular_distance">
        <path>/{NXentry}/QuickEXAFS/cristal_inter_reticular_distance</path>
    </item>
    <item key="delta_theta0">
        <path>/{NXentry}/QuickEXAFS/delta_theta_0</path>
    </item>
    <item key="theta">
        <path>/{NXentry}/QuickEXAFS/theta</path>
    </item>
    <item key="monochromator_name">
        <path>/{NXentry}/QuickEXAFS/monochromator_name</path>
    </item>
</map-def>

=== thiyagavit/passerelle/trunk/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/mappings/SoleilNeXus/temporary_local_files.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map-def SYSTEM "../../dtd/mapping_file.dtd">
<map-def name="TEMP_FLYSCAN" version="1.0.0">
  <item key="acquisition_sequence">
    <path>/{NXentry}</path>
    <call>CreateVirtualItem</call>
  </item>
  <item key="camera">
    <path>/{NXentry}/{NXinstrument}/{NXdetector}</path>
    <call>CreateVirtualItem</call>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="channelScale">
    <path>/{NXentry}/{NXinstrument}/{NXdetector}/channelScale</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="dark">
    <path>/{NXentry}/{NXinstrument}/{NXdetector}/intensityBlack</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="distance">
    <path>/{NXentry}/{NXinstrument}/{NXdetector}/distance</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="exposureTime">
    <path>/{NXentry}/{NXinstrument}/{NXdetector}/Exposure</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="shutterCloseDelay">
    <path>/{NXentry}/{NXinstrument}/{NXdetector}/ShutterCloseDelay</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="xBin">
    <path>/{NXentry}/{NXinstrument}/{NXdetector}/Xbin</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="yBin">
    <path>/{NXentry}/{NXinstrument}/{NXdetector}/Ybin</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="mi">
    <path>/{NXentry}/{NXinstrument}/{NXintensity_monitor}</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="gain">
    <path>/{NXentry}/{NXinstrument}/{NXintensity_monitor}/Gain</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="intensity">
    <path>/{NXentry}/{NXinstrument}/{NXintensity_monitor}/intensity</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="lambda">
    <path>/{NXentry}/{NXinstrument}/{NXmonochromator}/wavelength</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="energy">
    <path>/{NXentry}/{NXinstrument}/{NXmonochromator}/energy</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="spectrums_scienta">
    <path>/{NXentry}/{NXdata}/sumData*</path>
    <call>DataItemStackerByName</call>
    <call>HarvestSignalAttributes</call>
    <attribute name="equipment">
      <path>/{NXentry}/{NXinstrument}/Scienta*{NXdetector}</path>
      <call>HarvestEquipmentAttributes</call>
      <call>SelectNodeByRegionAttribute</call>
    </attribute>
    <attribute name="interpretation" value="spectrum"/>
  </item>
  <item key="spectrums_xia">
    <path>/{NXentry}/{NXdata}/channel*</path>
    <call>DataItemStackerByName</call>
    <call>HarvestSignalAttributes</call>
    <attribute name="equipment">
      <path>/{NXentry}/{NXinstrument}/Xia*{NXdetector}</path>
      <call>HarvestEquipmentAttributes</call>
      <call>SelectNodeByRegionAttribute</call>
    </attribute>
    <attribute name="interpretation" value="spectrum"/>
  </item>
  <item key="images">
    <path>/{NXentry}/{NXdata}/Image</path>
    <call>HarvestSignalAttributes</call>
    <attribute name="interpretation" value="image"/>
  </item>
  <item key="comments">
    <path>/{NXentry}/{NXsample}/comments/data</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
</map-def>

=== thiyagavit/passerelle/tags/V8.8.2/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/mappings/SoleilNeXus/antares_passerelle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map-def SYSTEM "../../dtd/mapping_file.dtd">
<map-def name="ANTARES_PASSERELLE" version="1.0.0">
  <item key="acquisition_sequence">
    <path>/</path>
    <call>CreateVirtualItem</call>
  </item>
  <item key="camera">
    <path>/{NXinstrument}/{NXdetector}</path>
    <call>CreateVirtualItem</call>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="channelScale">
    <path>/{NXinstrument}/{NXdetector}/channelScale</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="dark">
    <path>/{NXinstrument}/{NXdetector}/intensityBlack</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="distance">
    <path>/{NXinstrument}/{NXdetector}/distance</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="exposureTime">
    <path>/{NXinstrument}/{NXdetector}/Exposure</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="shutterCloseDelay">
    <path>/{NXinstrument}/{NXdetector}/ShutterCloseDelay</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="xBin">
    <path>/{NXinstrument}/NXdetector}/Xbin</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="yBin">
    <path>/{NXinstrument}/{NXdetector}/Ybin</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="sweeps">
    <path>/{NXinstrument}/{NXdetector}/sweeps</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="acquisitionMode">
    <path>/{NXinstrument}/{NXdetector}/mode</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="lensMode">
    <path>/{NXinstrument}/{NXdetector}/lensMode</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="passEnergy">
    <path>/{NXinstrument}/{NXdetector}/passEnergy</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="lowEnergy">
    <path>/{NXinstrument}/{NXdetector}/lowEnergy</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="highEnergy">
    <path>/{NXinstrument}/{NXdetector}/highEnergy</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="energyStep">
    <path>/{NXinstrument}/{NXdetector}/energyStep</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="stepTime">
    <path>/{NXinstrument}/{NXdetector}/stepTime</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="firstXChannel">
    <path>/{NXinstrument}/{NXdetector}/detectorFirstXChannel</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="lastXChannel">
    <path>/{NXinstrument}/{NXdetector}/detectorLastXChannel</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="firstYChannel">
    <path>/{NXinstrument}/{NXdetector}/detectorFirstYChannel</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="lastYChannel">
    <path>/{NXinstrument}/{NXdetector}/detectorLastYChannel</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="slices">
    <path>/{NXinstrument}/{NXdetector}/slices</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="sliceScale">
    <path>/{NXinstrument}/{NXdetector}/sliceScale</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="energyScale">
    <path>/{NXinstrument}/{NXdetector}/energyScale</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="mi">
    <path>/{NXinstrument}/{NXintensity_monitor}</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="gain">
    <path>/{NXinstrument}/{NXintensity_monitor}/Gain</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="intensity">
    <path>/{NXinstrument}/{NXintensity_monitor}/intensity</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="lambda">
    <path>/{NXinstrument}/{NXmonochromator}/wavelength</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="energy">
    <path>/{NXinstrument}/{NXmonochromator}/energy</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="exitSlits">
    <path>/{NXinstrument}/{NXmonochromator}/exitSlitAperture</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="motor_name">
    <path>/{NXinstrument}/{NXpositioner}</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="motor_position">
    <path>/{NXinstrument}/{NXpositioner}/raw_value</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="dataChannelScale">
    <path>/{NXdata}/channelScale*</path>
    <!-- <call>DataItemStackerByName</call> -->
    <call>HarvestSignalAttributes</call>
    <attribute name="equipment">
      <path>/{NXinstrument}/Scienta*{NXdetector}</path>
      <call>HarvestEquipmentAttributes</call>
      <call>SelectNodeByRegionAttribute</call>
    </attribute>
  </item>
  <item key="samplePhi">
    <path>/{NXdata}/phi*</path>
    <call>DataItemStackerByName</call>
    <call>HarvestSignalAttributes</call>
  </item>
  <item key="sampleTheta">
    <path>/{NXdata}/Theta</path>
    <call>DataItemStackerByName</call>
    <call>HarvestSignalAttributes</call>
  </item>
  <item key="apertureAngle">
    <path>/{NXdata}/sliceScale*</path>
    <!-- <call>DataItemStackerByName</call> -->
    <call>HarvestSignalAttributes</call>
    <attribute name="equipment">
      <path>/{NXinstrument}/Scienta*{NXdetector}</path>
      <call>HarvestEquipmentAttributes</call>
      <call>SelectNodeByRegionAttribute</call>
    </attribute>
  </item>
  <item key="images">
    <path>/{NXdata}/data*</path>
    <call>DataItemStackerByName</call>
    <call>HarvestSignalAttributes</call>
    <attribute name="equipment">
      <path>/{NXinstrument}/Scienta*{NXdetector}</path>
      <call>HarvestEquipmentAttributes</call>
      <call>SelectNodeByRegionAttribute</call>
    </attribute>
    <attribute name="interpretation" value="image"/>
  </item>
  <item key="spectrums_scienta">
    <path>/{NXdata}/sumData*</path>
    <call>DataItemStackerByName</call>
    <call>HarvestSignalAttributes</call>
    <attribute name="equipment">
      <path>/{NXinstrument}/Scienta*{NXdetector}</path>
      <call>HarvestEquipmentAttributes</call>
      <call>SelectNodeByRegionAttribute</call>
    </attribute>
    <attribute name="interpretation" value="spectrum"/>
  </item>
  <item key="spectrums_xia">
    <path>/{NXdata}/channel*</path>
    <call>DataItemStackerByName</call>
    <call>HarvestSignalAttributes</call>
    <attribute name="equipment">
      <path>/{NXinstrument}/Xia*{NXdetector}</path>
      <call>HarvestEquipmentAttributes</call>
      <call>SelectNodeByRegionAttribute</call>
    </attribute>
    <attribute name="interpretation" value="spectrum"/>
  </item>
  <item key="total_spectrum">
    <path>/Scienta_Total{NXdata}/total_sum_data</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="total_image">
    <path>/Scienta_Total{NXdata}/total_data</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="comments">
    <path>/comment_conditions/data</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
</map-def>

=== thiyagavit/passerelle/branches/passerelle-8.8/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/mappings/SoleilNeXus/cristal_scanserver.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map-def SYSTEM "../../dtd/mapping_file.dtd">
<map-def name="CRISTAL_SCANSERVER" version="1.0.0">

  <item key="acquisition_sequence">
    <path></path>
    <call>CreateVirtualItem</call>
  </item>
  <item key="camera">
    <path>/{NXinstrument}/{NXdetector}</path>
    <call>CreateVirtualItem</call>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="channelScale">
    <path>/{NXinstrument}/{NXdetector}/channelScale</path>
    <!-- set attributes as "acquisition_sequence", "region" and "instrument" works only with NXinstrument 
      children -->
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="liveTime">
    <path>/{NXinstrument}/{NXdetector}/liveTime*</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="dark">
    <path>/{NXinstrument}/{NXdetector}/intensityBlack</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="distance">
    <path>/{NXinstrument}/{NXdetector}/distance</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="exposureTime">
    <path>/{NXinstrument}/{NXdetector}/Exposure</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="shutterCloseDelay">
    <path>/{NXinstrument}/{NXdetector}/ShutterCloseDelay</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="xBin">
    <path>/{NXinstrument}/{NXdetector}/Xbin</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="yBin">
    <path>/{NXinstrument}/{NXdetector}/Ybin</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="sweeps">
    <path>/{NXinstrument}/{NXdetector}/sweeps</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="acquisitionMode">
    <path>/{NXinstrument}/{NXdetector}/mode</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="lensMode">
    <path>/{NXinstrument}/{NXdetector}/lensMode</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="passEnergy">
    <path>/{NXinstrument}/{NXdetector}/passEnergy</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="lowEnergy">
    <path>/{NXinstrument}/{NXdetector}/lowEnergy</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="highEnergy">
    <path>/{NXinstrument}/{NXdetector}/highEnergy</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="energyStep">
    <path>/{NXinstrument}/{NXdetector}/energyStep</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="stepTime">
    <path>/{NXinstrument}/{NXdetector}/stepTime</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="firstXChannel">
    <path>/{NXinstrument}/{NXdetector}/detectorFirstXChannel</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="lastXChannel">
    <path>/{NXinstrument}/{NXdetector}/detectorLastXChannel</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="firstYChannel">
    <path>/{NXinstrument}/{NXdetector}/detectorFirstYChannel</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="lastYChannel">
    <path>/{NXinstrument}/{NXdetector}/detectorLastYChannel</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="slices">
    <path>/{NXinstrument}/{NXdetector}/slices</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="sliceScale">
    <path>/{NXinstrument}/{NXdetector}/sliceScale</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="energyScale">
    <path>/{NXinstrument}/{NXdetector}/energyScale</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="dataChannelScale">
    <path>/{NXdata}/*channelScale*</path>
  </item>
  <item key="mi">
    <path>/{NXinstrument}/{NXintensity_monitor}</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="gain">
    <path>/{NXinstrument}/{NXintensity_monitor}/Gain</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="intensity">
    <path>/{NXinstrument}/{NXintensity_monitor}/intensity</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="energy">
    <path>/{NXinstrument}/{NXmonochromator}/energy</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="exitSlits">
    <path>/{NXinstrument}/{NXmonochromator}/exitSlitAperture</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="images">
    <!-- the core will try to open that path, but won't succeed -->
    <path>/{NXdata}/data_*@long_name=*image</path>
    <!-- that method will get the previous path from context, will split the attribute section from the 
      path to filter on that attribute name and value -->
    <call>AttributeFilter</call>
    <call>HarvestEquipmentAttributes</call>
    <attribute name="interpretation" value="image"/>
  </item>
  <item key="spectrums_scienta">
    <!-- the core will try to open that path, but won't succeed -->
    <path>/{NXdata}/data_*@long_name=*scienta/sumdata</path>
    <!-- that method will get the previous path from context, will split the attribute section from the 
      path to filter on that attribute name and value -->
    <call>AttributeFilter</call>
    <!-- fitting item listed above will be searched for their attribute "acquisition_sequence"... -->
    <call>HarvestEquipmentAttributes</call>
    <attribute name="equipment">
      <path>/{NXinstrument}/Scienta*{NXdetector}</path>
      <call>CreateVirtualItem</call>
      <call>HarvestEquipmentAttributes</call>
    </attribute>
    <attribute name="region">
      <path>/{NXinstrument}/Scienta*{NXdetector}</path>
      <call>CreateVirtualItem</call>
      <call>HarvestEquipmentAttributes</call>
    </attribute>
    <attribute name="interpretation" value="spectrum"/>
  </item>
  <item key="spectrums_xia">
    <path>/{NXdata}/data_*@long_name=*/channel*</path>
    <call>AttributeFilter</call>
    <call>HarvestEquipmentAttributes</call>
    <attribute name="equipment">
      <path>/{NXinstrument}/Xia*{NXdetector}</path>
      <call>CreateVirtualItem</call>
      <call>HarvestEquipmentAttributes</call>
    </attribute>
    <attribute name="interpretation" value="spectrum"/>
  </item>
  <item key="scalars_xia">
    <path>/{NXdata}/data_*@long_name=*/eventsinrun*</path>
    <call>AttributeFilter</call>
    <call>HarvestEquipmentAttributes</call>
    <attribute name="equipment">
      <path>/{NXinstrument}/Xia*{NXdetector}</path>
      <call>CreateVirtualItem</call>
      <call>HarvestEquipmentAttributes</call>
    </attribute>
  </item>
  <item key="beamEnergy">
    <path>/{NXdata}/actuator_*@long_name=*/energy*</path>
    <call>AttributeFilter</call>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="x_position">
    <path>/{NXdata}/trajectory_1_1</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="y_position">
    <path>/{NXdata}/trajectory_2_1</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="motor_name">
    <path>/{NXinstrument}/{NXpositioner}</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="motor_position">
    <path>/{NXinstrument}/{NXpositioner}/raw_value</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="comments">
    <path>/comment_conditions/data</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="end_time">
    <path>/start_time</path>
  </item>
  <item key="time">
    <path>/duration</path>
  </item>
</map-def>

=== thiyagavit/passerelle/branches/passerelle-8.5/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/mappings/SoleilNeXus/swing_passerelle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map-def SYSTEM "../../dtd/mapping_file.dtd">
<map-def name="SWING_PASSERELLE" version="1.0.0">
  <item key="acquisition_sequence">
    <path>/</path>
    <call>CreateVirtualItem</call>
  </item>
  <item key="camera">
    <path>/{NXinstrument}/{NXdetector}</path>
    <call>CreateVirtualItem</call>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="channelScale">
    <path>/{NXinstrument}/{NXdetector}/channelScale</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="dark">
    <path>/{NXinstrument}/{NXdetector}/intensityBlack</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="distance">
    <path>/{NXinstrument}/{NXdetector}/distance</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="exposureTime">
    <path>/{NXinstrument}/{NXdetector}/Exposure</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="shutterCloseDelay">
    <path>/{NXinstrument}/{NXdetector}/ShutterCloseDelay</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="xBin">
    <path>/{NXinstrument}/{NXdetector}/Xbin</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="yBin">
    <path>/{NXinstrument}/{NXdetector}/Ybin</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="mi">
    <path>/{NXinstrument}/{NXintensity_monitor}</path>
    <call>CreateVirtualItem</call>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="gain">
    <path>/{NXinstrument}/{NXintensity_monitor}/Gain</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="intensity">
    <path>/{NXinstrument}/{NXintensity_monitor}/intensity</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="lambda">
    <path>/{NXinstrument}/{NXmonochromator}/wavelength</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="energy">
    <path>/{NXinstrument}/{NXmonochromator}/energy</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
  <item key="images">
    <path>/image*{NXdata}/data</path>
    <call>DataItemStacker</call>
    <call>HarvestSignalAttributes</call>
    <attribute name="equipment">
      <path>/{NXinstrument}/{NXdetector}</path>
      <call>HarvestEquipmentAttributes</call>
    </attribute>
    <attribute name="interpretation" value="image"/>
  </item>
  <item key="comments">
    <path>/{NXsample}/comments/data</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
</map-def>

=== thiyagavit/passerelle/tags/V8.7.4/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/mappings/SoleilNeXus/hermes_scanserver.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map-def SYSTEM "../../dtd/mapping_file.dtd">
<map-def name="HERMES_SCANSERVER" version="1.0.0">
  <item key="acquisition_sequence">
    <path></path>
    <!-- create virtual data item having the name of the nodes listed above -->
    <call>CreateVirtualItem</call>
  </item>
  <item key="images">
    <path>/{NXdata}/data_03</path>
    <call>HarvestEquipmentAttributes</call>
    <attribute name="interpretation" value="image"/>
  </item>
  <item key="x_position">
    <path>/{NXdata}/time_1</path>
    <call>HarvestEquipmentAttributes</call>
  </item>
</map-def>
