=== thiyagavit/passerelle/branches/passerelle-8.8/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/dtd/view_file.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT data-def ( (group | item)*)>
<!ATTLIST data-def
    name CDATA #REQUIRED
    synonym CDATA #REQUIRED
    concept CDATA #IMPLIED
    version CDATA #IMPLIED
>

<!-- 
==========================
item
========================== 
-->
<!ELEMENT item EMPTY>
<!ATTLIST item 
    key CDATA #REQUIRED
>

<!-- 
==========================
group
========================== 
-->
<!ELEMENT group ( group*, item* )>
<!ATTLIST group 
    key CDATA #REQUIRED
>

=== thiyagavit/passerelle/tags/V8.6.0/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/views/data_reduction_view.xml
<!DOCTYPE data-def SYSTEM "../dtd/view_file.dtd">
<data-def name="DATA_REDUCTION" synonym="">
  <group key="scan">
    <group key="detector">
      <item key="camera" />
      <item key="dark" />
      <item key="distance" />
      <item key="exposureTime" />
      <item key="shutterCloseDelay" />
      <item key="xBin" />
      <item key="yBin" />
      <item key="channelScale" />
      <item key="liveTime" />
      <item key="sweeps" />
      <item key="acquisitionMode" />
      <item key="lensMode" />
      <item key="passEnergy" />
      <item key="lowEnergy" />
      <item key="highEnergy" />
      <item key="energyStep" />
      <item key="stepTime" />
      <item key="firstXChannel" />
      <item key="lastXChannel" />
      <item key="firstYChannel" />
      <item key="lastYChannel" />
      <item key="slices" />
      <item key="sliceScale" />
      <item key="energyScale" />
      <item key="dataChannelScale" />
    </group>
    <group key="monitor">
      <item key="mi" />
      <item key="gain" />
      <item key="intensity" />
    </group>
    <group key="monochromator">
      <item key="lambda" />
      <item key="energy" />
      <item key="exitSlits" />
    </group>
    <group key="motors">
      <item key="motor_name" />
      <item key="motor_position" />
    </group>
    <group key="data">
      <item key="images" />
      <item key="beamEnergy" />
      <item key="spectrums_xia" />
      <item key="spectrums_scienta" />
      <item key="scalars_xia" />
      <item key="total_spectrum" />
      <item key="total_image" />
      <item key="x_position" />
      <item key="y_position" />
      <item key="sampleTheta" />
      <item key="samplePhi" />
      <item key="apertureAngle" />
    </group>
    <group key="info">
      <item key="comments" />
    </group>
    <item key="acquisition_sequence" />
  </group>
</data-def>

=== thiyagavit/passerelle/branches/passerelle-8.9/contributions-actors/fr.soleil.passerelle.cdma.actor.test/CDMA_Dictionaries/views/quick_exafs_view.xml
<!DOCTYPE data-def SYSTEM "../dtd/view_file.dtd">
<data-def name="QUICK_EXAFS" synonym="">
	<item key="delta_theta"/> <!-- angle oscillation -->
    	<item key="intensity0"/>    <!-- current before sample -->
	<item key="intensity1"/>    <!-- current after sample -->
	<item key="intensity2"/>    <!-- current after sample -->
	<item key="mono2_direction"/>
	<item key="mono3_direction"/>
	<item key ="cristal_inter_reticular_distance"/>
	<item key ="delta_theta0"/>
	<item key ="theta"/>
	<item key ="monochromator_name"/>
</data-def>
